name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest

    #COMANDOS DE PERMISSÃO
    permissions:
      contents: write
      pull-requests: write
      issues: write    

    # O container do CML já vem com Python e ferramentas de ML instaladas
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Treinar Modelo e Gerar Relatório
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 1. Instalar dependências (caso não estejam no container)
          pip install pandas scikit-learn matplotlib seaborn numpy

          # 2. Rodar o seu script de treino
          python train.py

          echo "## Métricas do Modelo" > report.md
          cat metrics.txt >> report.md
          echo "## Visualizações" >> report.md
          echo "### Importância" >> report.md
          cml-publish feature_importance.png --md >> report.md
          cml-publish residuals.png --md >> report.md

          cml send-comment report.md